<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Samuel Ryan / citricsquid, UK web developer</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Personal website of Samuel Ryan / citricsquid" />
        <link rel="stylesheet" href="assets/css/bootstrap.min.css" type="text/css" />
        <link href='http://fonts.googleapis.com/css?family=Lato:300,400' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="assets/css/style.css" type="text/css" />
        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-29439846-14']);
            _gaq.push(['_trackPageview']);

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
        </script>
    </head>
    <body>
        <div class="container" id="wrapper">
            <header class="mb row">
                <div class="span8">
                    <h1 class="name">Samuel Ryan</h1> <!-- assets/img/samryan.jpg -->
                    <div class="span3" id="social">
                        <a href="https://twitter.com/citricsquid" class="twitter-follow-button" data-show-count="true">Follow @citricsquid</a>
                        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
                    </div>
                    <div class="clear"></div>
                </div>
            </header>
            <div class="row">
                <div id="photo">
                    <img src="assets/img/sam<?php echo rand(1,3); ?>.jpg" title="refresh for another" alt="sam"/>
                </div>
                <div class="span8" id="introduction">
                    <p>
                        I create, develop and manage websites. 
                        Currently working for 
                        <a class="curse" href="http://curse.com">Curse, Inc</a> 
                        where I manage the <a href="http://www.minecraftforum.net/forum">Minecraft Forum</a>, 
                        which I created (along with the <a href="http://www.minecraftwiki.net/">Minecraft Wiki</a>) 
                        in 2009, both were acquired in late 2010 by 
                        <a class="curse" href="http://curse.com">Curse, Inc</a>.
                        In total websites that I have founded have been viewed 
                        over <span title="billion, with a b">6,110,353,540</span> 
                        times, a selection of those websites is available below.
                    </p>
                    <p>
                        Located in England, reach via
                        <a href="mailto:sam@samryan.co.uk">sam@samryan.co.uk</a>.
                        My internet alias is <span class="citricsquid">citricsquid</span>,
                        I can be found on most sites as that 
                        (<a href="https://twitter.com/citricsquid">twitter</a>,
                        <a href="https://github.com/citricsquid">github</a>,
                        <a href="https://facebook.com/citricsquid">facebook</a> etc).
                    </p>
                </div>
            </div>
            <div class="row" id="sites">
                <?php foreach($this->projects as $project) { ?>
                <div class="site span8" style="background-image:url('assets/img/websites/<?php echo $project["background_image"]; ?>');">
                    <div class="heading">
                        <span class="title">
                            <?php if(isset($project["link"])) { ?>
                            <a href="<?php echo $project["link"]; ?>" title="<?php echo $project["name"]; ?>"><?php echo $project["name"]; ?></a>
                            <?php } else { echo $project["name"]; } ?>
                        </span>
                        <div class="roles">
                            <?php foreach($project["roles"] as $role => $type) { ?>
                            <span class="label <?php echo $type; ?>"><?php echo $role; ?></span>
                            <?php } ?>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="body">
                        <div class="description">
                            <?php echo nl2p($project["description"], false, true, false); ?>
                        </div>
                    </div>
                </div>
                <?php } ?>
            </div>
            <footer id="footer">
                <div style="float:right;">
                    <span class="love">&hearts;</span> from citricsquid &mdash; <a href="https://github.com/citricsquid/samryan.co.uk">sourcecode</a>
                </div>
                <div style="float:left;">
                    <a href="#">&uarr; top</a>
                </div>
                <div class="clear"></div>
            </footer>
        </div>
    </body>
</html>
